Fixing config file

diff --git a/react-project-apds/.circleci/config.yml b/react-project-apds/.circleci/config.yml
--- a/react-project-apds/.circleci/config.yml
+++ b/react-project-apds/.circleci/config.yml
@@ -42,12 +42,24 @@ jobs:
     working_directory: ~/project
     steps:
       - checkout
-      - run:
-          name: Install SonarScanner 4.0
+            - run:
+          name: Install SonarScanner 4.6.2
           command: |
-            curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.0.0.1743-linux.zip
+            curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
+            
+            if [ $? -ne 0 ]; then
+              echo "Error downloading SonarScanner. Exiting..."
+              exit 1
+            fi
+            
             unzip sonar-scanner-cli.zip -d $HOME
-            echo "export PATH=\$HOME/sonar-scanner-4.0.0.1743-linux/bin:\$PATH" >> $BASH_ENV
+            
+            if [ $? -ne 0 ]; then
+              echo "Error extracting SonarScanner. Exiting..."
+              exit 1
+            fi
+            
+            echo "export PATH=\$HOME/sonar-scanner-4.6.2.2472-linux/bin:\$PATH" >> $BASH_ENV
             source $BASH_ENV
       - run:
           name: Run SonarCloud analysis
